// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"usersvc/config"
	"usersvc/delivery/http"
	"usersvc/middleware"
	"usersvc/repository/mysqlrepo/impl"
	impl2 "usersvc/service/impl"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitDependency(config2 *config.StartupConfig) (*App, error) {
	taskDB, err := newCfAdminMysqlDbConnection(config2)
	if err != nil {
		return nil, err
	}
	userMySQLRepo := impl.NewUserMySQLRepo(taskDB)
	userService := impl2.NewUserService(userMySQLRepo)
	userHandler := http.NewUserHandler(userService)
	userMiddleware := middleware.NewUserMiddleware(userService, config2)
	echo, err := newRouter(userHandler, userMiddleware)
	if err != nil {
		return nil, err
	}
	app := newApp(config2, echo)
	return app, nil
}
